### ISSUE TITLE
service-worker.js

### ISSUE THREAD

**Issue by smarigowda** [jeffposnick/create-react-pwa#1]
where is service-worker.js stored?

**Comment by jeffposnick** [comment]
It's generated as part of the build process by the `sw-precache` command line tool. When used as illustrated in this repo, it will be written out to `build/service-worker.js`.

You can see an example of what gets generated in the `gh-pages` branch, which has a deployed version of the PWA: https://github.com/jeffposnick/create-react-pwa/blob/gh-pages/service-worker.js

**Comment by smarigowda** [comment]
Thank you
