### ISSUE TITLE
dontCacheBustUrlsMatching regex shouldn't match domain part?

### ISSUE THREAD

**Issue by bgrzys** [jeffposnick/create-react-pwa#14]
Hi,
Our main domain is 8 characters long, so it's matching default dontCacheBustUrlsMatching regex: "/\.\w{8}\./".

My workaround was to restrict this config to "/main\.\w{8}\./". This works for us, however I believe that proper solution would be to ignore domain part at all. Maybe just use relativeUrl instead of absoluteUrl in createCacheKey? What do you think?

**Comment by jeffposnick** [comment]
Good point. I'll track that at https://github.com/GoogleChrome/sw-precache/issues/240
