### ISSUE TITLE
Broken link to deployment site in README.md

### ISSUE THREAD

**Issue by arishuynhvan** [jeffposnick/create-react-pwa#22]
This [link https://jeffposnick.github.io/create-react-pwa/](https://jeffposnick.github.io/create-react-pwa/) is no longer accessible.

Please kindly fix the deployment or edit the documentation.

**Comment by jeffposnick** [comment]
Sorry! It should be working now. (Some things went amiss due to https://jeffy.info/2017/02/24/hosting-setup-revisited.html)
