### ISSUE TITLE
gh-pages no longer needed...

### ISSUE THREAD

**Issue by dandv** [jeffposnick/create-react-pwa#5]
...now that [GitHub allows publishing any directory from any branch](http://stackoverflow.com/questions/35978862/github-pages-why-do-i-need-a-gh-pages/39024307#39024307)?

> While not strictly necessary, a new npm run gh-pages script was added in, relying on the gh-pages module.

**Comment by jeffposnick** [comment]
Yup. I've left it out of the latest updates: https://github.com/jeffposnick/create-react-pwa/compare/c-r-a-0.6.0...c-r-pwa-0.6.0
