### ISSUE TITLE
Can't offline

### ISSUE THREAD

**Issue by ArvinH** [jeffposnick/create-react-pwa#6]
I follow README to add PWA support on my friend's webapp which is builded by create-react-app
I also add some modification for iOS safari support (in index.html, you may check here: https://github.com/ArvinH/type_instructor/blob/master/index.html#L7 )
cache-polyfill added too.

here's the link of webapp
https://blog.arvinh.info/type_instructor/

It looks good when it open from home screen and 
I can test it with chrome devtool on my mac (it will show my resource comes from service worker) 

but it doesn't work when my phone turn off nettwork
I also try a clean app: https://blog.arvinh.info/react-pwa-boilerplate/ 
doesn't work either.

the only workable sample I found is this one which is follow the google developer doc
https://github.com/lichin-lin/typhoonPWA/ (not use sw-precache)

and this one sometimes work (use offline-plugin for webpack):
https://github.com/paulhoughton/react-pwa 

Did I misunderstand something? seems like my service worker didn't work properly.

[screencast](http://g.recordit.co/1VJk3ZPcyY.gif)

**Comment by stereobooster** [comment]
Safari on iOS do not support [serviceworkers](http://caniuse.com/#feat=serviceworkers). iOS uses manifest as fallback

**Comment by ArvinH** [comment]
I noticed that...
I should close this one.
Thanks anyway.
