### ISSUE TITLE
Compatibility with latest create-react-app dependencies

### ISSUE THREAD

**Issue by camel113** [jeffposnick/create-react-pwa#7]
I am not sure to understand this sentence in your readme.
_When running a production server locally, make sure you use a different port than 3000, to ensure the service worker does not inadvertantly take control of the development environment._

Can we test service workers locally (with classic method `npm start`) with your changes?

**Comment by camel113** [comment]
I think your changes do not work with `"react-scripts": "0.7.0",`

**Comment by jeffposnick** [comment]
Thanks for the heads-up. I haven't had a chance to test this out with `react-scripts` 0.7.0 yet, and it's entirely possible that the setup needs to be modified. I'll keep this issue open to track that.

(I need a little time to get to it, though.)

**Comment by nikhildev** [comment]
I have react-scripts 0.7.0 as well, and looks like the manifest is getting served with the mime type as text/html. Is there any work around for this?

**Comment by jeffposnick** [comment]
I've updated things with an example of using the latest `create-react-app` dependency.

Can you take a look at https://github.com/jeffposnick/create-react-pwa/compare/c-r-a-0.6.0...c-r-pwa-0.6.0 and confirm that making those changes to something scaffolded with the latest `create-react-app` works for you?

**Comment by jeffposnick** [comment]
I've heard from other folks that have confirmed it's working now. Please reopen this issue if you're still seeing issues with `react-scripts` 0.7.0.

**Comment by camel113** [comment]
Thank you @jeffposnick I do not find the time to check it but I will do it soon ;-) As you said other folks confirmed so I trust them ;-)
