### ISSUE TITLE
How to run the code please?

### ISSUE THREAD

**Issue by edouardbrasier** [jeffposnick/create-react-pwa#9]
Hi Jeff,

I have downloaded the code and tried to use it the same way as https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html

I have tried from the node command 
1/ Cd my folder
2/ npm start

It doesn't work. I get the error message

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! create-react-pwa@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-react-pwa@0.1.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the create-react-pwa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs create-react-pwa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls create-react-pwa
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Progressive\pwa\npm-debug.log

**Comment by cfenzo** [comment]
Hi,

It seems like you haven't run `npm install` in the project folder yet.
Try that before running `npm start` :)

**Comment by edouardbrasier** [comment]
Thanks a lot! It is working now.
A small update of the doc with detailed step to step for beginners like me would be useful : )
